//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KommFlex.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KommFlex.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KommFlex.
        /// </summary>
        internal static string APPLICATION_NAME {
            get {
                return ResourceManager.GetString("APPLICATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_down {
            get {
                object obj = ResourceManager.GetObject("arrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_left {
            get {
                object obj = ResourceManager.GetObject("arrow_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_right {
            get {
                object obj = ResourceManager.GetObject("arrow_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_up {
            get {
                object obj = ResourceManager.GetObject("arrow_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to background.png.
        /// </summary>
        internal static string BACKGROUND_FILE_NAME {
            get {
                return ResourceManager.GetString("BACKGROUND_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config.xml.
        /// </summary>
        internal static string CONFIG_FILE_NAME {
            get {
                return ResourceManager.GetString("CONFIG_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndpointId.
        /// </summary>
        internal static string CONFIG_ITEM_NAME_ENDPOINT_ID {
            get {
                return ResourceManager.GetString("CONFIG_ITEM_NAME_ENDPOINT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PictureDisplayApp.
        /// </summary>
        internal static string CONFIG_ITEM_NAME_PICTURE_DISPLAY_APP {
            get {
                return ResourceManager.GetString("CONFIG_ITEM_NAME_PICTURE_DISPLAY_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PictureFolder.
        /// </summary>
        internal static string CONFIG_ITEM_NAME_PICTURE_FOLDER {
            get {
                return ResourceManager.GetString("CONFIG_ITEM_NAME_PICTURE_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PictureWidth.
        /// </summary>
        internal static string CONFIG_ITEM_NAME_PICTURE_WIDTH {
            get {
                return ResourceManager.GetString("CONFIG_ITEM_NAME_PICTURE_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrimaryCamera.
        /// </summary>
        internal static string CONFIG_ITEM_NAME_PRIMARY_CAMERA {
            get {
                return ResourceManager.GetString("CONFIG_ITEM_NAME_PRIMARY_CAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RingTimeout.
        /// </summary>
        internal static string CONFIG_ITEM_NAME_RING_TIMEOUT {
            get {
                return ResourceManager.GetString("CONFIG_ITEM_NAME_RING_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecondaryCamera.
        /// </summary>
        internal static string CONFIG_ITEM_NAME_SECONDARY_CAMERA {
            get {
                return ResourceManager.GetString("CONFIG_ITEM_NAME_SECONDARY_CAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerURL.
        /// </summary>
        internal static string CONFIG_ITEM_NAME_SERVER_URL {
            get {
                return ResourceManager.GetString("CONFIG_ITEM_NAME_SERVER_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StationId.
        /// </summary>
        internal static string CONFIG_ITEM_NAME_STATION_ID {
            get {
                return ResourceManager.GetString("CONFIG_ITEM_NAME_STATION_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string DEFAULT_DISPATCHER_VIDEO_DISPLAY_MODE {
            get {
                return ResourceManager.GetString("DEFAULT_DISPATCHER_VIDEO_DISPLAY_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        internal static string DEFAULT_PHOTO_FOLDER {
            get {
                return ResourceManager.GetString("DEFAULT_PHOTO_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mspaint.exe.
        /// </summary>
        internal static string DEFAULT_PHOTO_VIEWER {
            get {
                return ResourceManager.GetString("DEFAULT_PHOTO_VIEWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string DEFAULT_PRIMARY_CAMERA {
            get {
                return ResourceManager.GetString("DEFAULT_PRIMARY_CAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60.
        /// </summary>
        internal static string DEFAULT_RING_TIMEOUT {
            get {
                return ResourceManager.GetString("DEFAULT_RING_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string DEFAULT_SECONDARY_CAMERA {
            get {
                return ResourceManager.GetString("DEFAULT_SECONDARY_CAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01.
        /// </summary>
        internal static string DEFAULT_STATION_ID {
            get {
                return ResourceManager.GetString("DEFAULT_STATION_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_2ndcam {
            get {
                object obj = ResourceManager.GetObject("icon-2ndcam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_2ndcam_disabled {
            get {
                object obj = ResourceManager.GetObject("icon-2ndcam-disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_camera {
            get {
                object obj = ResourceManager.GetObject("icon-camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_camera_disabled {
            get {
                object obj = ResourceManager.GetObject("icon-camera-disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_decline {
            get {
                object obj = ResourceManager.GetObject("icon-decline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_exit {
            get {
                object obj = ResourceManager.GetObject("icon-exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_exit_disabled {
            get {
                object obj = ResourceManager.GetObject("icon-exit-disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_person {
            get {
                object obj = ResourceManager.GetObject("icon-person", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_sendmsg {
            get {
                object obj = ResourceManager.GetObject("icon-sendmsg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_sendmsg_disabled {
            get {
                object obj = ResourceManager.GetObject("icon-sendmsg-disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Központ hívása folyamatban....
        /// </summary>
        internal static string MSG_TEXT_CALLING_CENTRAL_DISPATCHER {
            get {
                return ResourceManager.GetString("MSG_TEXT_CALLING_CENTRAL_DISPATCHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyógyszerész hívása folyamatban.
        /// </summary>
        internal static string MSG_TEXT_CALLING_DISPATCHER {
            get {
                return ResourceManager.GetString("MSG_TEXT_CALLING_DISPATCHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem található gyógyszerész! Kérjük egyeztessen a rendszergazdával!.
        /// </summary>
        internal static string MSG_TEXT_CANNOT_FIND_DISPATCHER {
            get {
                return ResourceManager.GetString("MSG_TEXT_CANNOT_FIND_DISPATCHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A szerver URL cím nem található!.
        /// </summary>
        internal static string MSG_TEXT_CANNOT_FIND_SERVER {
            get {
                return ResourceManager.GetString("MSG_TEXT_CANNOT_FIND_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kérem állítsa be a konfigurációt.
        /// </summary>
        internal static string MSG_TEXT_CHECK_CONFIG {
            get {
                return ResourceManager.GetString("MSG_TEXT_CHECK_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szerverkapcsolati hiba miatt az alkalmazást be kell zárni!.
        /// </summary>
        internal static string MSG_TEXT_CLOSED_APP_CONNECTION_ERR {
            get {
                return ResourceManager.GetString("MSG_TEXT_CLOSED_APP_CONNECTION_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapcsolódás a szerverhez....
        /// </summary>
        internal static string MSG_TEXT_CONNECTING_TO_SERVER {
            get {
                return ResourceManager.GetString("MSG_TEXT_CONNECTING_TO_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A szerverhez nem lehet kapcsolódni!.
        /// </summary>
        internal static string MSG_TEXT_FAIL_CONNECTION {
            get {
                return ResourceManager.GetString("MSG_TEXT_FAIL_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem irányítható át a központhoz, mert az nem elérhető!.
        /// </summary>
        internal static string MSG_TEXT_FAIL_REDIRECTING_CALL {
            get {
                return ResourceManager.GetString("MSG_TEXT_FAIL_REDIRECTING_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A kép készítése nem sikerült!.
        /// </summary>
        internal static string MSG_TEXT_FAIL_TAKING_PHOTO {
            get {
                return ResourceManager.GetString("MSG_TEXT_FAIL_TAKING_PHOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A kép feltöltése sikertelen!.
        /// </summary>
        internal static string MSG_TEXT_FAIL_UPLOADING_PHOTO {
            get {
                return ResourceManager.GetString("MSG_TEXT_FAIL_UPLOADING_PHOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejövő hívás.
        /// </summary>
        internal static string MSG_TEXT_INCOMMING_CALL {
            get {
                return ResourceManager.GetString("MSG_TEXT_INCOMMING_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kérem adja meg a végpont azonosítóját!.
        /// </summary>
        internal static string MSG_TEXT_INPUT_ENDPOINT_ID {
            get {
                return ResourceManager.GetString("MSG_TEXT_INPUT_ENDPOINT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azonosító:.
        /// </summary>
        internal static string MSG_TEXT_INPUT_ENDPOINT_ID_LABLE {
            get {
                return ResourceManager.GetString("MSG_TEXT_INPUT_ENDPOINT_ID_LABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kérem adja meg a szerver címét!.
        /// </summary>
        internal static string MSG_TEXT_INPUT_SERVER_URL {
            get {
                return ResourceManager.GetString("MSG_TEXT_INPUT_SERVER_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL:.
        /// </summary>
        internal static string MSG_TEXT_INPUT_SERVER_URL_LABEL {
            get {
                return ResourceManager.GetString("MSG_TEXT_INPUT_SERVER_URL_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs hívható kliens!.
        /// </summary>
        internal static string MSG_TEXT_NO_CLIENT {
            get {
                return ResourceManager.GetString("MSG_TEXT_NO_CLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs hívható gyógyszerész!.
        /// </summary>
        internal static string MSG_TEXT_NO_DISPATCHER {
            get {
                return ResourceManager.GetString("MSG_TEXT_NO_DISPATCHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kérem nyomja meg a gombot a hívásindításhoz!.
        /// </summary>
        internal static string MSG_TEXT_PRESS_BUTTON {
            get {
                return ResourceManager.GetString("MSG_TEXT_PRESS_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Készen áll a hívásfogadásra..
        /// </summary>
        internal static string MSG_TEXT_READY_CALL {
            get {
                return ResourceManager.GetString("MSG_TEXT_READY_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Átirányítás a központba....
        /// </summary>
        internal static string MSG_TEXT_REDIRECTING_CALL {
            get {
                return ResourceManager.GetString("MSG_TEXT_REDIRECTING_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A kép sikeresen elkészült..
        /// </summary>
        internal static string MSG_TEXT_SUCCESS_TAKING_PHOTO {
            get {
                return ResourceManager.GetString("MSG_TEXT_SUCCESS_TAKING_PHOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kép készítése folyamatban....
        /// </summary>
        internal static string MSG_TEXT_TAKING_CLIENT_PHOTO {
            get {
                return ResourceManager.GetString("MSG_TEXT_TAKING_CLIENT_PHOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kép készítése folyamatban....
        /// </summary>
        internal static string MSG_TEXT_TAKING_PHOTO {
            get {
                return ResourceManager.GetString("MSG_TEXT_TAKING_PHOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream ring {
            get {
                return ResourceManager.GetStream("ring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowLocation.
        /// </summary>
        internal static string WINDOW_LOCATION {
            get {
                return ResourceManager.GetString("WINDOW_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowMaximized.
        /// </summary>
        internal static string WINDOW_MAXIMIZED {
            get {
                return ResourceManager.GetString("WINDOW_MAXIMIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowMinimized.
        /// </summary>
        internal static string WINDOW_MINIMIZED {
            get {
                return ResourceManager.GetString("WINDOW_MINIMIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowSize.
        /// </summary>
        internal static string WINDOW_SIZE {
            get {
                return ResourceManager.GetString("WINDOW_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowState.
        /// </summary>
        internal static string WINDOW_STATE {
            get {
                return ResourceManager.GetString("WINDOW_STATE", resourceCulture);
            }
        }
    }
}
